allowBuilds:
  "@scarf/scarf": true
  esbuild: true
  msw: true
minimumReleaseAgeExclude:
  - "@voidzero-dev/vite-plus-core@0.2.8"
  - "@voidzero-dev/vite-plus-darwin-arm64@0.2.8"
  - "@voidzero-dev/vite-plus-darwin-x64@0.2.8"
  - "@voidzero-dev/vite-plus-linux-arm64-gnu@0.2.8"
  - "@voidzero-dev/vite-plus-linux-arm64-musl@0.2.8"
  - "@voidzero-dev/vite-plus-linux-x64-gnu@0.2.8"
  - "@voidzero-dev/vite-plus-linux-x64-musl@0.2.8"
  - "@voidzero-dev/vite-plus-win32-arm64-msvc@0.2.8"
  - "@voidzero-dev/vite-plus-win32-x64-msvc@0.2.8"
  - vite-plus@0.2.8
  - '@base-ui/react@1.7.0'
  - '@base-ui/utils@0.3.2'
