name: "✅ Check"
on:
  push:
    branches:
      - main
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - ready_for_review

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  check:
    name: "🔬 Vite+ checks"
    runs-on: ubuntu-latest
    timeout-minutes: 20
    if: ${{ !github.event.pull_request.draft || github.event_name == 'push' }}
    steps:
      - name: "📥 Checkout repo"
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false
      - name: "⚙️ Setup Node and pnpm"
        uses: pnpm/setup@fbda4c85fc2e1e08721cd8763afea8f48d60f024 # v3.0.0
        with:
          node-version-file: .node-version
          cache: true
          install: false
      - name: "📥 Install dependencies"
        run: pnpm install --frozen-lockfile
      - name: "🔬 Check"
        run: pnpm exec vp check

  test:
    name: "🔎 Tests"
    runs-on: ubuntu-latest
    timeout-minutes: 30
    if: ${{ !github.event.pull_request.draft || github.event_name == 'push' }}
    steps:
      - name: "📥 Checkout repo"
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false
      - name: "⚙️ Setup Node and pnpm"
        uses: pnpm/setup@fbda4c85fc2e1e08721cd8763afea8f48d60f024 # v3.0.0
        with:
          node-version-file: .node-version
          cache: true
          install: false
      - name: "📥 Install dependencies"
        run: pnpm install --frozen-lockfile
      - name: "🎭 Install Playwright browsers"
        run: pnpm exec playwright install chromium chromium-headless-shell
      - name: "🔎 Unit tests"
        run: CI=1 pnpm run test
      - name: "🔎 Integration tests"
        run: CI=1 pnpm run test:integration

  build:
    name: "🔨 Build"
    runs-on: ubuntu-latest
    timeout-minutes: 20
    if: ${{ !github.event.pull_request.draft || github.event_name == 'push' }}
    steps:
      - name: "📥 Checkout repo"
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false
      - name: "⚙️ Setup Node and pnpm"
        uses: pnpm/setup@fbda4c85fc2e1e08721cd8763afea8f48d60f024 # v3.0.0
        with:
          node-version-file: .node-version
          cache: true
          install: false
      - name: "📥 Install dependencies"
        run: pnpm install --frozen-lockfile
      - name: "🔨 Build"
        run: pnpm run build
